services:
  - type: web
    name: fantasycpu
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn thanos:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12

  - type: cron
    name: fantasycpu-cron
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python cron_job.py
    schedule: "0 5 * * *"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
