services:
  - type: web
    name: fantasycpu
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 thanos:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: YAHOO_CLIENT_ID
        sync: false
      - key: YAHOO_CLIENT_SECRET
        sync: false
      - key: YAHOO_TEAM_KEY
        sync: false
      - key: YAHOO_REFRESH_TOKEN
        sync: false
      - key: SPORTSGAMEODDS_API_KEY
        sync: false
      - key: SPORTSDATAIO_API_KEY
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: TOMORROWIO_API_KEY
        sync: false
      - key: VISUALCROSSING_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: STORMGLASS_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
